import { useMemo, useState } from 'react';
import { Modal, Pressable, ScrollView, TextInput, View } from 'react-native';
import { AppText } from './AppText';
import { Card } from './Card';
import { useAppTheme } from '@/theme/useAppTheme';
import { AppIcon } from '@/components/art/AppIcon';

const fallback = ['UTC','Australia/Brisbane','Australia/Sydney','Australia/Melbourne','Australia/Perth','America/Chicago','America/New_York','America/Los_Angeles','Europe/London','Europe/Paris','Asia/Tokyo','Asia/Singapore'];
function zones() { try { const fn=(Intl as unknown as { supportedValuesOf?: (key:string)=>string[] }).supportedValuesOf; return fn ? fn('timeZone') : fallback; } catch { return fallback; } }
function offset(zone:string) { try { const parts=new Intl.DateTimeFormat('en-US',{timeZone:zone,timeZoneName:'shortOffset'}).formatToParts(new Date()); return parts.find((p)=>p.type==='timeZoneName')?.value ?? ''; } catch { return ''; } }
export function TimezonePickerField({ value, onChange, label='TIMEZONE' }:{value:string;onChange:(value:string)=>void;label?:string}) {
  const theme=useAppTheme(); const [open,setOpen]=useState(false); const [query,setQuery]=useState('');
  const all=useMemo(()=>zones(),[]); const filtered=useMemo(()=>all.filter((z)=>z.toLowerCase().includes(query.toLowerCase())).slice(0,120),[all,query]);
  return <View style={{gap:8}}><AppText variant="caption" tone="secondary">{label}</AppText><Pressable accessibilityRole="button" onPress={()=>setOpen(true)}><Card tone="secondary" style={{paddingVertical:12,paddingHorizontal:14,flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><View style={{flex:1}}><AppText>{value}</AppText><AppText variant="caption" tone="muted">{offset(value)}</AppText></View><AppIcon name="chevron" size={16} color={theme.colors.textMuted} /></Card></Pressable><Modal visible={open} transparent animationType="fade" onRequestClose={()=>setOpen(false)}><View style={{flex:1,backgroundColor:'rgba(0,0,0,.72)',justifyContent:'center',padding:20}}><Card style={{maxHeight:'78%',gap:12}}><View style={{flexDirection:'row',alignItems:'center'}}><AppText variant="section" style={{flex:1}}>Choose timezone</AppText><Pressable accessibilityRole="button" onPress={()=>setOpen(false)}><AppText tone="accent">Done</AppText></Pressable></View><TextInput value={query} onChangeText={setQuery} placeholder="Search city or region" placeholderTextColor={theme.colors.textMuted} style={{color:theme.colors.textPrimary,backgroundColor:theme.colors.elevatedBackground,borderRadius:theme.radii.md,paddingHorizontal:14,paddingVertical:12,fontSize:16}}/><ScrollView keyboardShouldPersistTaps="handled">{filtered.map((zone)=><Pressable key={zone} accessibilityRole="button" onPress={()=>{onChange(zone);setOpen(false);setQuery('')}} style={({pressed})=>({paddingVertical:12,opacity:pressed?0.6:1})}><View style={{flexDirection:'row',gap:12}}><AppText style={{flex:1}}>{zone.replaceAll('_',' ')}</AppText><AppText variant="caption" tone="muted">{offset(zone)}</AppText></View></Pressable>)}</ScrollView></Card></View></Modal></View>;
}
